### PR TITLE
Added a log message for onCreate. Plus Duy is awesome.

### PR DESCRIPTION
**Pull request by ddh**
Just Do It!

### CODE REVIEW

**Comment by Reagankm** [comment]
Nice description

**Comment by gurs1kh** [comment]
Don't let your dreams be dreams!

**Comment by sutjin** [comment]
Yesterday you said tomorrow!

**Comment by sutjin** [comment]
shia-labeouf

**Comment by ddh** [comment]
Just Do It!

**Comment by gurs1kh** [comment]
Some people dream of success, while you’re going to wake up and work hard at it! Nothing is impossible!

**Pull request closed without merging**
